# Generated by Django 5.2.3 on 2025-06-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
