# Generated by Django 5.2.3 on 2025-07-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='listing_type',
            field=models.CharField(choices=[('normal', 'Normal Listing ($10)'), ('priority', 'Priority Listing ($20)')], default='normal', max_length=10),
        ),
    ]
