# Generated by Django 5.2.3 on 2025-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('airbnb', 'Airbnb'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
