# Generated by Django 5.2.3 on 2025-07-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_default_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps link for confirmed location', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('normal', 'Normal Listing ($10)'), ('priority', 'Priority Listing ($20)')], default='normal', help_text='Type of listing for this property', max_length=10),
        ),
    ]
