# Generated by Django 5.2.3 on 2025-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
