# Generated by Django 5.2.3 on 2025-07-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_google_maps_url_alter_property_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Airbnb', 'Airbnb'), ('Room', 'Room'), ('Guesthouse', 'Guesthouse')], max_length=20, null=True),
        ),
    ]
