# Generated by Django 5.2.3 on 2025-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('airbnb', 'Airbnb'), ('room', 'Room'), ('guesthouse', 'Guesthouse')], max_length=20, null=True),
        ),
    ]
