# Generated by Django 5.2.3 on 2025-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_property_additional_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('airbnb', 'Airbnb')], max_length=20, null=True),
        ),
    ]
