# Generated by Django 5.2.3 on 2025-07-22 06:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="state_or_region",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
