# Generated by Django 5.2.3 on 2026-02-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_property_country_property_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="current_step",
        ),
    ]
