# Generated by Django 5.2.3 on 2025-06-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_propertyimage_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='main_image',
            new_name='image',
        ),
    ]
