# Generated by Django 5.2.3 on 2025-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_main_image_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_main_images/'),
        ),
    ]
