# Generated by Django 5.2.3 on 2025-06-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_propertyimage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_main_images/'),
        ),
    ]
