# Generated by Django 5.2.3 on 2025-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_currency_property_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(default='check', help_text="Font Awesome icon name (e.g. 'wifi', 'tv', 'swimming-pool')", max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
