"""
Django settings for tourwise_website project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['d8fd3aff7b04.ngrok-free.app', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://d8fd3aff7b04.ngrok-free.app/',
    'https://*.ngrok-free.app',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'listings',
    'payments',
    # 'behave_django',  # Commented out - optional testing framework
    'widget_tweaks',
    # 'currencies',  # Commented out - not found/not needed
    'chatbot',  # AI-powered chatbot for property search assistance
    'django.contrib.gis',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tourwise_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tourwise_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Neon Database Configuration
tmpPostgres = urlparse(os.getenv("DATABASE_URL") or "")

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',  # Using PostGIS for geospatial features
        'NAME': tmpPostgres.path.lstrip('/') if tmpPostgres.path else '',
        'USER': tmpPostgres.username or '',
        'PASSWORD': tmpPostgres.password or '',
        'HOST': tmpPostgres.hostname or '',
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)) if tmpPostgres.query else {},
        'CONN_MAX_AGE': 600,  # Connection pooling: keep connections open for 10 minutes
        'CONN_HEALTH_CHECKS': True,  # Check connection health before reuse
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Maximum size for uploaded files (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrPhoneBackend',  # custom
    'django.contrib.auth.backends.ModelBackend',  # fallback
]

# GDAL/GEOS Libraries - Required for Django GeoDjango
# Even with Neon PostGIS, Django needs local GEOS for geometry object handling
# Try tourwise-env first, then fall back to base anaconda
env_paths = [
    r'C:\ProgramData\anaconda3\envs\tourwise-env',
    r'C:\ProgramData\anaconda3',
]

# Find the first path that has GEOS library
CONDA_PREFIX = None
for path in env_paths:
    geos_path = os.path.join(path, 'Library', 'bin', 'geos_c.dll')
    if os.path.exists(geos_path):
        CONDA_PREFIX = path
        break

if CONDA_PREFIX is None:
    # Default to env path even if file doesn't exist (will error later with clear message)
    CONDA_PREFIX = env_paths[0]

GEOS_LIBRARY_PATH = os.path.join(CONDA_PREFIX, 'Library', 'bin', 'geos_c.dll')
GDAL_LIBRARY_PATH = os.path.join(CONDA_PREFIX, 'Library', 'bin', 'gdal.dll')

# API Keys
# GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')  # Removed - using free Nominatim for location search
GROQ_API_KEY = os.getenv('GROQ_API_KEY')

# Paynow Settings
PAYNOW_INTEGRATION_ID = os.getenv('PAYNOW_INTEGRATION_ID', '21331')
PAYNOW_INTEGRATION_KEY = os.getenv('PAYNOW_INTEGRATION_KEY')
PAYNOW_RETURN_URL = os.getenv('PAYNOW_RETURN_URL', 'http://127.0.0.1/payments/complete/')
PAYNOW_RESULT_URL = os.getenv('PAYNOW_RESULT_URL', 'http://127.0.0.1/payments/update/')
PAYNOW_MODE = os.getenv('PAYNOW_MODE', 'test')

# Development-specific settings
if DEBUG:
    # Use localhost URLs for development
    PAYNOW_RETURN_URL = os.getenv('DEV_PAYNOW_RETURN_URL', 'http://localhost:8000/payments/complete/')
    PAYNOW_RESULT_URL = os.getenv('DEV_PAYNOW_RESULT_URL', 'http://localhost:8000/payments/update/')

    # Enable detailed logging for Paynow
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'payments': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }

    # Validation for required environment variables
    REQUIRED_ENV_VARS = [
        # 'GOOGLE_API_KEY',  # Removed - using free Nominatim
        'SECRET_KEY',
        'DATABASE_URL',
        'PAYNOW_INTEGRATION_KEY',
        'GROQ_API_KEY'
    ]

    missing_vars = [var for var in REQUIRED_ENV_VARS if not os.getenv(var)]
    if missing_vars:
        raise ValueError(f"Missing required environment variables: {', '.join(missing_vars)}")