# Generated by Django 5.2.3 on 2025-07-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_cbdlocation_conversationstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="has_ai_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[("user", "User"), ("bot", "Bot"), ("system", "System")],
                max_length=10,
            ),
        ),
    ]
